/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ILiquidator2 } from "../ILiquidator2";

export class ILiquidator2__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILiquidator2 {
    return new Contract(address, _abi, signerOrProvider) as ILiquidator2;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ILoanToken2Deprecated",
        name: "loan",
        type: "address",
      },
    ],
    name: "legacyLiquidate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IDebtToken[]",
        name: "debts",
        type: "address[]",
      },
    ],
    name: "liquidate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
